-- Vericonomy Explorer - Postgres schema (per-chain LIST partitioning by chain_id)
--
-- Design notes:
--   * Every table is range/list-partitioned on chain_id so VRM and VRC live in
--     physically separate child tables (blocks_vrm / blocks_vrc, ...). This gives
--     per-chain autovacuum, partition pruning, and independent maintenance while
--     keeping a single logical query surface (WHERE chain_id = $1 prunes to one child).
--   * *_sats columns are BIGINT (64-bit). The Node layer parses int8 -> BigInt so
--     value math stays exact. SUM() promotes to NUMERIC and is parsed as string.
--   * 0/1 flags stay SMALLINT to match the existing JS semantics (Number(flag) === 0).
--   * raw_json is retained (nullable) but NOT migrated from SQLite; RPC fallback
--     reconstructs raw payloads on demand.
--
-- Apply with: psql "$VCEXP_PG_URL" -v ON_ERROR_STOP=1 -f schema.sql

BEGIN;

CREATE TABLE IF NOT EXISTS indexer_meta (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS chains (
    id                    TEXT PRIMARY KEY,
    ticker                TEXT NOT NULL UNIQUE,
    name                  TEXT NOT NULL,
    network               TEXT NOT NULL DEFAULT 'main',
    consensus             TEXT NOT NULL,
    rpc_capabilities_json TEXT,
    created_at            BIGINT NOT NULL,
    updated_at            BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS sync_state (
    chain_id            TEXT NOT NULL,
    best_rpc_height     BIGINT,
    last_indexed_height BIGINT,
    last_indexed_hash   TEXT,
    last_checked_height BIGINT,
    status              TEXT NOT NULL DEFAULT 'idle',
    status_message      TEXT,
    updated_at          BIGINT NOT NULL,
    PRIMARY KEY (chain_id)
);

-- ---------------------------------------------------------------------------
-- Partitioned core chain data
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS blocks (
    chain_id            TEXT NOT NULL,
    height              BIGINT NOT NULL,
    hash                TEXT NOT NULL,
    previous_hash       TEXT,
    next_hash           TEXT,
    time                BIGINT NOT NULL,
    tx_count            BIGINT NOT NULL DEFAULT 0,
    size                BIGINT,
    difficulty          TEXT,
    chainwork_or_trust  TEXT,
    flags               TEXT,
    status              TEXT NOT NULL DEFAULT 'main',
    raw_json            TEXT,
    indexed_at          BIGINT NOT NULL,
    output_count        BIGINT,
    extracted_by        TEXT,
    extracted_by_address TEXT,
    fee_sats            BIGINT,
    total_output_sats   BIGINT,
    PRIMARY KEY (chain_id, height),
    UNIQUE (chain_id, hash)
) PARTITION BY LIST (chain_id);

CREATE TABLE IF NOT EXISTS transactions (
    chain_id      TEXT NOT NULL,
    txid          TEXT NOT NULL,
    block_height  BIGINT NOT NULL,
    block_hash    TEXT NOT NULL,
    tx_index      BIGINT NOT NULL,
    time          BIGINT NOT NULL,
    is_coinbase   SMALLINT NOT NULL DEFAULT 0,
    is_coinstake  SMALLINT NOT NULL DEFAULT 0,
    raw_available SMALLINT NOT NULL DEFAULT 0,
    source        TEXT NOT NULL DEFAULT 'index',
    raw_json      TEXT,
    indexed_at    BIGINT NOT NULL,
    PRIMARY KEY (chain_id, txid)
) PARTITION BY LIST (chain_id);

CREATE TABLE IF NOT EXISTS vouts (
    chain_id       TEXT NOT NULL,
    txid           TEXT NOT NULL,
    n              BIGINT NOT NULL,
    address        TEXT,
    value_sats     BIGINT NOT NULL DEFAULT 0,
    script_type    TEXT,
    script_pub_key TEXT,
    spent_by_txid  TEXT,
    spent_by_vin   BIGINT,
    spent_height   BIGINT,
    is_spent       SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (chain_id, txid, n)
) PARTITION BY LIST (chain_id);

CREATE TABLE IF NOT EXISTS vout_addresses (
    chain_id      TEXT NOT NULL,
    txid          TEXT NOT NULL,
    n             BIGINT NOT NULL,
    address       TEXT NOT NULL,
    address_index BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (chain_id, txid, n, address)
) PARTITION BY LIST (chain_id);

CREATE TABLE IF NOT EXISTS vins (
    chain_id   TEXT NOT NULL,
    txid       TEXT NOT NULL,
    n          BIGINT NOT NULL,
    prev_txid  TEXT,
    prev_vout  BIGINT,
    address    TEXT,
    value_sats BIGINT,
    source     TEXT NOT NULL DEFAULT 'index',
    resolved   SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (chain_id, txid, n)
) PARTITION BY LIST (chain_id);

CREATE TABLE IF NOT EXISTS address_events (
    chain_id     TEXT NOT NULL,
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    address      TEXT NOT NULL,
    txid         TEXT NOT NULL,
    block_height BIGINT NOT NULL,
    time         BIGINT NOT NULL,
    delta_sats   BIGINT NOT NULL,
    event_type   TEXT NOT NULL,
    source       TEXT NOT NULL DEFAULT 'index',
    created_at   BIGINT NOT NULL,
    PRIMARY KEY (chain_id, id)
) PARTITION BY LIST (chain_id);

CREATE TABLE IF NOT EXISTS address_transactions (
    chain_id          TEXT NOT NULL,
    address           TEXT NOT NULL,
    txid              TEXT NOT NULL,
    first_seen_height BIGINT NOT NULL,
    first_seen_time   BIGINT NOT NULL,
    created_at        BIGINT NOT NULL,
    net_delta_sats    BIGINT,
    PRIMARY KEY (chain_id, address, txid)
) PARTITION BY LIST (chain_id);

CREATE TABLE IF NOT EXISTS address_balances (
    chain_id            TEXT NOT NULL,
    address             TEXT NOT NULL,
    balance_sats        BIGINT NOT NULL DEFAULT 0,
    total_received_sats BIGINT NOT NULL DEFAULT 0,
    total_sent_sats     BIGINT NOT NULL DEFAULT 0,
    tx_count            BIGINT NOT NULL DEFAULT 0,
    last_seen_height    BIGINT,
    first_seen_height   BIGINT,
    first_seen_time     BIGINT,
    updated_at          BIGINT NOT NULL,
    PRIMARY KEY (chain_id, address)
) PARTITION BY LIST (chain_id);

CREATE TABLE IF NOT EXISTS richlist_snapshots (
    chain_id        TEXT NOT NULL,
    snapshot_height BIGINT NOT NULL,
    snapshot_time   BIGINT NOT NULL,
    rank            BIGINT NOT NULL,
    address         TEXT NOT NULL,
    balance_sats    BIGINT NOT NULL,
    created_at      BIGINT NOT NULL,
    PRIMARY KEY (chain_id, snapshot_height, rank)
) PARTITION BY LIST (chain_id);

CREATE TABLE IF NOT EXISTS address_period_stats (
    chain_id        TEXT NOT NULL,
    period          TEXT NOT NULL,
    period_start    BIGINT NOT NULL,
    period_end      BIGINT NOT NULL,
    address         TEXT NOT NULL,
    received_sats   BIGINT NOT NULL DEFAULT 0,
    sent_sats       BIGINT NOT NULL DEFAULT 0,
    net_sats        BIGINT NOT NULL DEFAULT 0,
    tx_count        BIGINT NOT NULL DEFAULT 0,
    last_seen_height BIGINT,
    last_seen_time  BIGINT,
    rank_received   BIGINT,
    rank_net        BIGINT,
    updated_at      BIGINT NOT NULL,
    PRIMARY KEY (chain_id, period, period_start, address)
) PARTITION BY LIST (chain_id);

CREATE TABLE IF NOT EXISTS chain_activity_buckets (
    chain_id       TEXT NOT NULL,
    bucket_start   BIGINT NOT NULL,
    mined_count    BIGINT NOT NULL DEFAULT 0,
    staked_count   BIGINT NOT NULL DEFAULT 0,
    received_count BIGINT NOT NULL DEFAULT 0,
    block_count    BIGINT NOT NULL DEFAULT 0,
    updated_at     BIGINT NOT NULL,
    PRIMARY KEY (chain_id, bucket_start)
) PARTITION BY LIST (chain_id);

CREATE TABLE IF NOT EXISTS address_balance_buckets (
    chain_id      TEXT NOT NULL,
    address       TEXT NOT NULL,
    bucket_start  BIGINT NOT NULL,
    mined_sats    BIGINT NOT NULL DEFAULT 0,
    staked_sats   BIGINT NOT NULL DEFAULT 0,
    received_sats BIGINT NOT NULL DEFAULT 0,
    spent_sats    BIGINT NOT NULL DEFAULT 0,
    delta_sats    BIGINT NOT NULL DEFAULT 0,
    updated_at    BIGINT NOT NULL,
    PRIMARY KEY (chain_id, address, bucket_start)
) PARTITION BY LIST (chain_id);

CREATE TABLE IF NOT EXISTS network_metric_buckets (
    chain_id                    TEXT NOT NULL,
    bucket_start                BIGINT NOT NULL,
    difficulty                  DOUBLE PRECISION,
    block_height                BIGINT,
    supply                      DOUBLE PRECISION,
    hashrate_kh_per_min         DOUBLE PRECISION,
    interest_rate_percent       DOUBLE PRECISION,
    net_stake_weight            DOUBLE PRECISION,
    percent_staked              DOUBLE PRECISION,
    expected_stake_time_seconds BIGINT,
    address_count               BIGINT,
    updated_at                  BIGINT NOT NULL,
    PRIMARY KEY (chain_id, bucket_start)
) PARTITION BY LIST (chain_id);

-- ---------------------------------------------------------------------------
-- Incremental analytics rollup layer (maintained by refreshAnalytics.js)
-- ---------------------------------------------------------------------------

-- Per-(chain, rollup) watermark so the cron refresher advances only new data
-- instead of rebuilding from scratch. `last_height` / `last_event_id` are the
-- high-water marks of the source rows already folded into each rollup.
CREATE TABLE IF NOT EXISTS rollup_state (
    chain_id      TEXT NOT NULL,
    rollup        TEXT NOT NULL,
    last_height   BIGINT NOT NULL DEFAULT -1,
    last_event_id BIGINT NOT NULL DEFAULT 0,
    last_time     BIGINT NOT NULL DEFAULT 0,
    extra_json    TEXT,
    updated_at    BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (chain_id, rollup)
);

-- Daily per-miner rollup powering the top-miners leaderboard. Rolling windows
-- (7d/30d/90d/year/all) are served by summing day buckets >= the cutoff day,
-- replacing the all-coinbase scan with an indexed top-N over a tiny table.
CREATE TABLE IF NOT EXISTS miner_stats (
    chain_id     TEXT NOT NULL,
    address      TEXT NOT NULL,
    day_start    BIGINT NOT NULL,
    blocks_mined BIGINT NOT NULL DEFAULT 0,
    mined_sats   BIGINT NOT NULL DEFAULT 0,
    last_height  BIGINT NOT NULL DEFAULT 0,
    updated_at   BIGINT NOT NULL,
    PRIMARY KEY (chain_id, address, day_start)
) PARTITION BY LIST (chain_id);

COMMIT;
